/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./src/components/ui/global/ActionsMenu.vue')['default']
    Avatar: typeof import('./src/components/ui/global/Avatar.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('./src/components/ui/global/Checkbox.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    DateTimePicker: typeof import('./src/components/ui/global/DateTimePicker.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    ErrorToast: typeof import('./src/components/ui/global/ErrorToast.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Galleria: typeof import('primevue/galleria')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Input: typeof import('./src/components/ui/global/Input.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('./src/components/ui/global/InputNumber.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('./src/components/ui/global/MultiSelect.vue')['default']
    OptionsDropdown: typeof import('./src/components/ui/local/OptionsDropdown.vue')['default']
    ProfileBadge: typeof import('./src/components/ui/local/ProfileBadge.vue')['default']
    ProfileMenu: typeof import('./src/components/ui/local/ProfileMenu.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/global/Select.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    SuccessToast: typeof import('./src/components/ui/global/SuccessToast.vue')['default']
    Switch: typeof import('./src/components/ui/global/Switch.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Text: typeof import('./src/components/ui/global/Text.vue')['default']
  }
}
