/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./src/components/ui/global/ActionsMenu.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    ErrorToast: typeof import('./src/components/ui/global/ErrorToast.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Input: typeof import('./src/components/ui/global/Input.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    OptionsDropdown: typeof import('./src/components/ui/local/OptionsDropdown.vue')['default']
    Password: typeof import('./src/components/ui/global/Password.vue')['default']
    ProfileBadge: typeof import('./src/components/ui/local/ProfileBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/global/Select.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    SuccessToast: typeof import('./src/components/ui/global/SuccessToast.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Text: typeof import('./src/components/ui/global/Text.vue')['default']
  }
}
