/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/global/Avatar.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('./src/components/ui/global/Checkbox.vue')['default']
    DateTimePicker: typeof import('./src/components/ui/global/DateTimePicker.vue')['default']
    EmailList: typeof import('./src/components/ui/global/EmailList.vue')['default']
    ErrorToast: typeof import('./src/components/ui/global/ErrorToast.vue')['default']
    Input: typeof import('./src/components/ui/global/Input.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('./src/components/ui/global/MultiSelect.vue')['default']
    OptionsDropdown: typeof import('./src/components/ui/local/OptionsDropdown.vue')['default']
    Password: typeof import('./src/components/ui/global/Password.vue')['default']
    ProfileBadge: typeof import('./src/components/ui/local/ProfileBadge.vue')['default']
    ProfileMenu: typeof import('./src/components/ui/local/ProfileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/global/Select.vue')['default']
    SelectSwitchButton: typeof import('./src/components/ui/global/SelectSwitchButton.vue')['default']
    SuccessToast: typeof import('./src/components/ui/global/SuccessToast.vue')['default']
    Switch: typeof import('./src/components/ui/global/Switch.vue')['default']
    Text: typeof import('./src/components/ui/global/Text.vue')['default']
  }
}
