name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup SSH Key
      working-directory: umit-mobilya-server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy backend code to EC2
      run: |
        rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' \
        -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
        ./ ubuntu@${{ secrets.EC2_IP_ADDRESS }}:~/app

    - name: Restart Backend Service
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP_ADDRESS }} "sudo systemctl restart myapp.service"
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP_ADDRESS }} "sudo systemctl status myapp.service"
